version: '3.8'
services:
  postgres:
    container_name: card-app-db
    image: postgres:14.1-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cards
    ports:
      - '1111:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  loopback:
    build: .
    container_name: card-app-loopback
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres"
    ports: 
      - '1337:3000'
    environment:
      - NODE_ENV=docker
